
services:
  scanpix:
    build:
      context: .
      dockerfile: Dockerfile
    image: scanpix-server
    ports:
      - "5001:5001"
    volumes:
      - "./data:/scanpix/data"
  indexer:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: indexer-service
    ports:
      - "5000:5000"
    volumes:
      - "./data:/worker-app/data"
