
services:
  scanpix:
    build:
      context: .
      dockerfile: Dockerfile
    image: scanpix-server
    ports:
      - "5001:5001"
    volumes:
      - "./.directories:/scanpix/.directories"
      - "./data/index.json:/scanpix/index.json"
      - "/Users/adithya.bennur/SideHustles/scanpix/data/images:/scanpix/images"
      - "/Users/adithya.bennur/SideHustles/scanpix/ml:/scanpix/ml"

  indexer:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: indexer-service
    ports:
      - "5000:5000"
    volumes:
      - "./.directories:/worker-app/.directories"
      - "./data/index.json:/worker-app/index.json"
      - "/Users/adithya.bennur/SideHustles/scanpix/data/images:/worker-app/images"
      - "/Users/adithya.bennur/SideHustles/scanpix/ml:/worker-app/ml"

