version: '3'
services:
  scanpix-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: scanpix-server
    ports:
      - "5001:5001"
    volumes:
      - ./data:/scanpix/data
      - ./models:/scanpix/models
    environment:
    - MODE=${MODE}
  scanpix-indexer:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: scanpix-indexer
    profiles:
      - demo
      - index
    ports:
      - "5000:5000"
    volumes:
      - ./data:/worker-app/data
    environment:
    - MODE=${MODE}
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    profiles:
      - demo
    ports:
      - 8000:8000
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/www/data
      - ./data/images:/scanpix/data/images
      - /etc/ssl:/etc/ssl
    restart: always

networks:
  default:
    name: scanpix_network
