services:
  scanpix-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: scanpix-server:1.0
    ports:
      - "5001:5001"
    volumes:
      - "./data:/scanpix/data"
  indexer-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: indexer-service:1.0
    volumes:
      - ".data:/worker-app/data"
