version: '3'
services:
  scanpix-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: scanpix-server:1.0
    ports:
      - "5001:5001"
    volumes:
      - ./data:/scanpix/data
      - ./models:/scanpix/models
    environment:
    - MODE=${MODE}
  reverse-proxy:
    image: nginx:latest
    container_name: docker_nginx
    profiles:
      - demo
    ports:
      - 8000:8000
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/www/data
      - ./data/images:/scanpix/data/images
      - /etc/ssl:/etc/ssl
    restart: always
